name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install boost
      run: sudo apt-get install libboost-thread-dev
    
    - name: build
      run: g++ -std=c++11 -Wall -Wextra -pthread -o testchecker BMS_Core/*.* BMS_Sender/*.*
      
    - name: run
      run: ./testchecker
      
